### getAll 
GET http://127.0.0.1:3000/api/v1/tt
Content-Type: application/json
X-Api-Key: 3TYxPB7oS4PyG6YGi1aaqVjK
X-Api-Secret: 231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7a


### get a record
GET http://127.0.0.1:3000/api/v1/tt/1
Content-Type: application/json
X-Api-Key: 3TYxPB7oS4PyG6YGi1aaqVjK
X-Api-Secret: 231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7a

### create a record
POST http://127.0.0.1:3000/api/v1/tt
Content-Type: application/json
X-Api-Key: 3TYxPB7oS4PyG6YGi1aaqVjK
X-Api-Secret: 231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7a

{
  "name": "John Doe",
  "age": 30
}



### Update a record with avatar

PUT http://127.0.0.1:3000/api/v1/tt/2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
X-Api-Key: 3TYxPB7oS4PyG6YGi1aaqVjK
X-Api-Secret: 231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7a

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="test_image.jpg"
Content-Type: image/jpeg

< ./spec/fixtures/files/test_image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### delete a record
DELETE http://127.0.0.1:3000/api/v1/ttt/1
Content-Type: application/json
X-Api-Key: 3TYxPB7oS4PyG6YGi1aaqVjK
X-Api-Secret: 231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7aContent-Type: application/json

# apikey=3TYxPB7oS4PyG6YGi1aaqVjK
# apisecret=231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7a


### Update a record with name, age, and avatar
PUT http://127.0.0.1:3000/api/v1/tt/2
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
X-Api-Key: 3TYxPB7oS4PyG6YGi1aaqVjK
X-Api-Secret: 231081212d56550534493800f15db66519cf613551a2ce47f6daa936f2681b7a

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Jane Doe Updated
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="age"

35
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="test_image.jpg"
Content-Type: image/jpeg

< ./spec/fixtures/files/test_image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--